apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-tutorial-api
  name: ai-tutorial-api-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ai-tutorial-api
  type: LoadBalancer
